### ISSUE TITLE
Rework settings.yaml

### ISSUE THREAD

**Issue by ptylczynski** [CaddoBenchmark/data-factory#3]
We should to rework settings.yaml to contain more descriptive names

## Implementation suggestion
```yaml
data:
  input:
    path: data.csv
    separator: $
  extraction:
    function:
      path: extraction_function
  output:
    file:
      name: results.csv
      separator: $
  splitting:
    folding:
      method: KFOLDS
      seeds:
        from_list: [1,2,3,4,5]
```
